### PR TITLE
Change Pinecone for langchain's wrapper for FAISS

### PR DESCRIPTION
**Pull request by doncamilom**
This change replaces pinecone for langchain's wrapper for FAISS vector database.
With this users don't have to get another API key and it makes it all easier to set up.

hope it helps :)

### CODE REVIEW

**Comment by Josh-XT** [comment]
Big improvement in my opion.

**Review by Josh-XT — APPROVED** [review]
LGTM

**Comment by donQx** [comment]
http://{OOBA_SERVER}:7860/run/textgen   this "run/textgen"  doesnt work as an endpoint , what am i doing wrong

**Comment by donQx** [comment]
it returns: 
{'error': 'This app has no endpoint /api/textgen/.'}

**Comment by Josh-XT** [comment]
> it returns: {'error': 'This app has no endpoint /api/textgen/.'}
Start server like this, but replace `your-model` with your model name.

`python3 server.py --model your-model --listen --no-stream`

**Comment by donQx** [comment]
Thx, yeah i Had to remove the Chat Argument. Any Chance on autogpt with local Models?😀

**Comment by Josh-XT** [comment]
> Thx, yeah i Had to remove the Chat Argument. Any Chance on autogpt with local Models?😀

Not yet. If they'll slow down on development for long enough for me to add support for it, I will haha.

**Pull request closed without merging**
