### PR TITLE
More agents, shared context, terminal access, and python, javascript, css capabilities

### PR DESCRIPTION
**Pull request by ordas21**
The create_python_developer_agent, create_javascript_developer_agent, create_researcher_agent, create_css_developer_agent, create_custom_agent, and prioritization_agent functions were moved from the agents.py file to a new agent_module.py file.

AHHHH SO MUCH STUFF HAPPENING SO FAST!!!!
CONTRIBUTE AND WE WILL SOON HAVE THE SINGULARITY

### CODE REVIEW

**Comment by ordas21** [comment]
Task ---> MAIN AGENT --pick agent for task---> SUB AGENT ---> Makes more stuff

**Comment by francip** [comment]
All those seem like cool important additions, but is it possible to split into smaller chunks so it's easier to review and merge?

**Comment by ordas21** [comment]
> All those seem like cool important additions, but is it possible to split into smaller chunks so it's easier to review and merge?

I can try but I've changed so much at this point idk how to break it up into smaller chunks lol

**Comment by kyleshrader** [comment]
> > All those seem like cool important additions, but is it possible to split into smaller chunks so it's easier to review and merge?
> 
> I can try but I've changed so much at this point idk how to break it up into smaller chunks lol

This generally means it is also difficult for others to understand or properly discuss the PR.

**Comment by kyleshrader** [comment]
Also I would recommend adding `__pycache__/` to your gitignore and removing them from your tracked files.

**Comment by LucasRodriguez** [comment]
Would also be helpful for you to update the readme on how to best take advantage of the changes you have made. Im trying to review but not super sure exactly what you are trying to build

**Comment by ordas21** [comment]
Im working on documenting all my changes. Kinda rushed to make a PR so that
anyone that has better ideas can contribute, while I improve my
documentation the main goal of this PR is to transition babyagi into a
“Terminal-GPT”. Giving babyagi access to the terminal would create endless
possibilities in terms of development. I want to give it the ability to
read and write files directly onto your computer. The “agents” serve as GPT
calls that perform very specific tasks. I’m building the plane as I fly it
so it’s very chaotic, but with this PR i was able to tell babyagi to create
a react project and then write JavaScript components that can then be added
to the project. Very cool stuff, I’ll be afk until Sunday CST, but I can
reply to any questions.

**Comment by tnachen** [comment]
It seems like the direction of the project is to keep a simple base and allow everyone to extend. So I think big changes like this is hard to go that direction. Probably better to rebase after the main refactor is done by @francip

**Comment by ordas21** [comment]
> It seems like the direction of the project is to keep a simple base and allow everyone to extend. So I think big changes like this is hard to go that direction. Probably better to rebase after the main refactor is done by @francip 

That's fair enough, I can close my PR if needed but if anyone wants to help develop the "terminal-gpt" fork I'll be maintaining it until someone makes something better. The idea is a GPT that has control of the terminal and hence your entire computer. I'll improve the documentation and commenting. I'll add a new read me as well. I do believe this is fork will be a critical step in making a true "GPT dev".

**Comment by ordas21** [comment]
Added tons more documentation, I hope that helps. Feel free to contribute, very buggy but GPT will write commands to the terminal and write python scripts.

**Comment by francip** [comment]
So I love the idea of adding terminal access to BabyAGI. I also like some of your refactors. But as @kyleshrader mentioned it, it's too big and too complex of a PR and it's unclear how to judge it.

I'd say bite the bullet and try to split this into smaller chunks. The more you delay, the less chance we'll ever get to a point where we can merge, because things will diverge more and more.

**Comment by francip** [comment]
I'd say drop the readme changes for now, remove the __pycache__ files, and let's focus on how we can split the babyagi.py changes.

**Comment by sebastiankurvers** [comment]
I think it's a great idea, but the shared context makes pinecone very expensive. Would it be possible to find another solution? Maybe exchange pinecone?

**Comment by francip** [comment]
There are couple of folks working on replacing Pinecone with a local vector DB (Weaviate or Chroma)

**Comment by ordas21** [comment]
What parts of the refactor do you like? If you guys want to keep babyagi simple I can just include the parts that you like and keep the larger changes separate. For instance the task module is something I can push on its own. Just lmk what you like and I'll make a new PR with only those changes. Cheers!

**Comment by ordas21** [comment]
> I think it's a great idea, but the shared context makes pinecone very expensive. Would it be possible to find another solution? Maybe exchange pinecone? 

Very good point, I've been looking into incorporating a local vector

**Comment by francip** [comment]
@ordas21 so finally got to replacing Pinecone with Chroma (though Pinecone still is available). Do you want to try refactoring this PR into smaller, or should I try to piece out some of those on my own?

**Comment by ordas21** [comment]
> @ordas21 so finally got to replacing Pinecone with Chroma (though Pinecone still is available). Do you want to try refactoring this PR into smaller, or should I try to piece out some of those on my own?

Feel free to take any work I did here!!

**Pull request closed without merging**
