### PR TITLE
Call LLaMA model with llama_cpp python binding

### PR DESCRIPTION
**Pull request by jakvb**
Use llama.cpp compatible python binding library
https://github.com/abetlen/llama-cpp-python

Install from PyPI:

pip install llama-cpp-python

### CODE REVIEW

**Comment by francip** [comment]
I definitely like this better than my hack. :-) But can you update the requirements.txt, and also the readme.md with instructions how to setup llama.cpp to work with the Python bindings?

**Review by francip — COMMENTED** [review]
Like it, but as is requires too much knowledge about llama.cpp setup. See my other comment.

**Comment by CRCODE22** [comment]
> I definitely like this better than my hack. :-) But can you update the requirements.txt, and also the readme.md with instructions how to setup llama.cpp to work with the Python bindings?

If you manage to get llama.cpp to work with the Python bindings which I did you will still have the openai api key problem

`(babyagi) D:\babyagi>python babyagi.py --Llama
llama.cpp: loading model from D:/babyagi/models/ggml-vicuna-7b-1.1-q4_1.bin
llama_model_load_internal: format = ggjt v1 (latest)
llama_model_load_internal: n_vocab = 32000
llama_model_load_internal: n_ctx = 2048
llama_model_load_internal: n_embd = 4096
llama_model_load_internal: n_mult = 256
llama_model_load_internal: n_head = 32
llama_model_load_internal: n_layer = 32
llama_model_load_internal: n_rot = 128
llama_model_load_internal: ftype = 3 (mostly Q4_1)
llama_model_load_internal: n_ff = 11008
llama_model_load_internal: n_parts = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size = 59.11 KB
llama_model_load_internal: mem required = 6612.57 MB (+ 1026.00 MB per state)
....................................................................................................
llama_init_from_file: kv self size = 1024.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |

OBJECTIVE

Solve world hunger

Initial task: Develop a task list

TASK LIST

1: Develop a task list

NEXT TASK

1: Develop a task list
Traceback (most recent call last):
File "D:\babyagi\babyagi.py", line 289, in
result = execution_agent(OBJECTIVE, task["task_name"])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\babyagi\babyagi.py", line 240, in execution_agent
context = context_agent(query=objective, top_results_num=5)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\babyagi\babyagi.py", line 262, in context_agent
query_embedding = get_ada_embedding(query)
^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\babyagi\babyagi.py", line 141, in get_ada_embedding
return openai.Embedding.create(input=[text], model="text-embedding-ada-002")[
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\anaconda3\envs\babyagi\Lib\site-packages\openai\api_resources\embedding.py", line 33, in create
response = super().create(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\anaconda3\envs\babyagi\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
response, _, api_key = requestor.request(
^^^^^^^^^^^^^^^^^^
File "E:\anaconda3\envs\babyagi\Lib\site-packages\openai\api_requestor.py", line 226, in request
resp, got_stream = self._interpret_response(result, stream)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\anaconda3\envs\babyagi\Lib\site-packages\openai\api_requestor.py", line 620, in _interpret_response
self._interpret_response_line(
File "E:\anaconda3\envs\babyagi\Lib\site-packages\openai\api_requestor.py", line 683, in _interpret_response_line
raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
`

**Comment by CRCODE22** [comment]
Ok seems I did not have the latest commit which I do now but then it throws another error and does not even get to the api key:

SyntaxError: Non-UTF-8 code starting with '\x95' in file D:\babyagi\babyagi.py on line 361, but no encoding declared; see https://peps.python.org/pep-0263/ for details

**Comment by CRCODE22** [comment]
> Ok seems I did not have the latest commit which I do now but then it throws another error and does not even get to the api key:
> 
> SyntaxError: Non-UTF-8 code starting with '\x95' in file D:\babyagi\babyagi.py on line 361, but no encoding declared; see https://peps.python.org/pep-0263/ for details

I fixed this problem by changing the following things locally in the babyagi.py

Adding # -*- coding: utf-8 -*- to line:2

And I added this around line 361

for t in tasks_storage.get_task_names():
    # Replace any non-UTF-8 characters in the task name with a question mark
    t = t.encode('ascii', 'replace').decode('ascii')
    print(" • " + t)

**Comment by CRCODE22** [comment]
> Ok seems I did not have the latest commit which I do now but then it throws another error and does not even get to the api key:
> 
> SyntaxError: Non-UTF-8 code starting with '\x95' in file D:\babyagi\babyagi.py on line 361, but no encoding declared; see https://peps.python.org/pep-0263/ for details

I fixed this problem by making the following changes locally in the babyagi.py

Adding # -- coding: utf-8 -- to line:2

**Comment by CRCODE22** [comment]
It is running now but the problem it keeps stuck in a loop doing the same task over and over again here is a preview more can be seen in the attached text file below:

ou are an AI who performs one task based on the following objective: Solve world hunger
.
    Take into account these previously completed tasks: ['Develop a task list']
.
    Your task: \\n    Take into account these previously completed tasks: []\\n.\\n    Your task: Develop a task list\\nResponse:\\n    100\\n\\n    Task List:\\n    1. Create a sustainable food production system that can produce enough food to feed the entire population of the world, including developing countries and remote areas. This will involve using new technologies such as vertical farming and hydroponics, as well as traditional farming methods.\\n    2. Implement policies that encourage people to eat more plant-based diets, which are better for the environment and can help reduce food waste. This could include subsidies for farmers who grow fruits and vegetables, and education campaigns to promote the benefits of'}.", '    This result was based on this task description: Develop a task list. These are incomplete tasks: .', '    Based on the result, create new tasks to be completed by the AI system that do not overlap with incomplete tasks.', '    Return the tasks as an array.', '    ', '    """', '    # Get the list of all completed tasks and their results', '    completed_tasks = get_completed_tasks()', '    ', '    # Create a new task list', '    new_tasks = []', '    ', '    # Iterate through each completed task', '    for task in completed_tasks:', '        # Check if the task is related to solving world hunger', '        if "world hunger" in task["objective"]:', '            # Get the previous task ID and its result', '            previous_task = get_previous_completed_task(task["id"])'].
Response: 100
Task List:
1. Create a sustainable food production system that can produce enough food to feed the entire population of the world, including developing countries and remote areas. This will involve using new technologies such as vertical farming and hydroponics, as well as traditional farming methods.
2. Implement policies that encourage people to eat more plant-based diets, which are better for the environment and can help reduce food waste. This could include subsidies for farmers who grow fruits and vegetables, and education campaigns to promote the benefits of eating more plants.

[(babyagi) Dbabyagipython babyagi.py.txt](https://github.com/yoheinakajima/babyagi/files/11290657/babyagi.Dbabyagipython.babyagi.py.txt)

**Comment by CRCODE22** [comment]
It is running now but the problem it keeps stuck in a loop doing the same task over and over again here is a preview more can be seen in the attached text file below:

You are an AI who performs one task based on the following objective: Solve world hunger
.
Take into account these previously completed tasks: ['Develop a task list']
.
Your task: \n Take into account these previously completed tasks: []\n.\n Your task: Develop a task list\nResponse:\n 100\n\n Task List:\n 1. Create a sustainable food production system that can produce enough food to feed the entire population of the world, including developing countries and remote areas. This will involve using new technologies such as vertical farming and hydroponics, as well as traditional farming methods.\n 2. Implement policies that encourage people to eat more plant-based diets, which are better for the environment and can help reduce food waste. This could include subsidies for farmers who grow fruits and vegetables, and education campaigns to promote the benefits of'}.", ' This result was based on this task description: Develop a task list. These are incomplete tasks: .', ' Based on the result, create new tasks to be completed by the AI system that do not overlap with incomplete tasks.', ' Return the tasks as an array.', ' ', ' """', ' # Get the list of all completed tasks and their results', ' completed_tasks = get_completed_tasks()', ' ', ' # Create a new task list', ' new_tasks = []', ' ', ' # Iterate through each completed task', ' for task in completed_tasks:', ' # Check if the task is related to solving world hunger', ' if "world hunger" in task["objective"]:', ' # Get the previous task ID and its result', ' previous_task = get_previous_completed_task(task["id"])'].
Response: 100
Task List:

    Create a sustainable food production system that can produce enough food to feed the entire population of the world, including developing countries and remote areas. This will involve using new technologies such as vertical farming and hydroponics, as well as traditional farming methods.
    Implement policies that encourage people to eat more plant-based diets, which are better for the environment and can help reduce food waste. This could include subsidies for farmers who grow fruits and vegetables, and education campaigns to promote the benefits of eating more plants.

[(babyagi) Dbabyagipython babyagi.py.txt](https://github.com/yoheinakajima/babyagi/files/11290657/babyagi.Dbabyagipython.babyagi.py.txt)

[(babyagi) Dbabyagipython babyagi.py.txt](https://github.com/yoheinakajima/babyagi/files/11290665/babyagi.Dbabyagipython.babyagi.py.txt)

**Comment by CRCODE22** [comment]
It is running now but the problem it keeps stuck in a loop doing the same task over and over again here is a preview more can be seen in the attached text file below:

You are an AI who performs one task based on the following objective: Solve world hunger
.
Take into account these previously completed tasks: ['Develop a task list']
.
Your task: \n Take into account these previously completed tasks: []\n.\n Your task: Develop a task list\nResponse:\n 100\n\n Task List:\n 1. Create a sustainable food production system that can produce enough food to feed the entire population of the world, including developing countries and remote areas. This will involve using new technologies such as vertical farming and hydroponics, as well as traditional farming methods.\n 2. Implement policies that encourage people to eat more plant-based diets, which are better for the environment and can help reduce food waste. This could include subsidies for farmers who grow fruits and vegetables, and education campaigns to promote the benefits of'}.", ' This result was based on this task description: Develop a task list. These are incomplete tasks: .', ' Based on the result, create new tasks to be completed by the AI system that do not overlap with incomplete tasks.', ' Return the tasks as an array.', ' ', ' """', ' # Get the list of all completed tasks and their results', ' completed_tasks = get_completed_tasks()', ' ', ' # Create a new task list', ' new_tasks = []', ' ', ' # Iterate through each completed task', ' for task in completed_tasks:', ' # Check if the task is related to solving world hunger', ' if "world hunger" in task["objective"]:', ' # Get the previous task ID and its result', ' previous_task = get_previous_completed_task(task["id"])'].
Response: 100
Task List:

    Create a sustainable food production system that can produce enough food to feed the entire population of the world, including developing countries and remote areas. This will involve using new technologies such as vertical farming and hydroponics, as well as traditional farming methods.
    Implement policies that encourage people to eat more plant-based diets, which are better for the environment and can help reduce food waste. This could include subsidies for farmers who grow fruits and vegetables, and education campaigns to promote the benefits of eating more plants.

[(babyagi) Dbabyagipython babyagi.py.txt](https://github.com/yoheinakajima/babyagi/files/11290667/babyagi.Dbabyagipython.babyagi.py.txt)

**Comment by CRCODE22** [comment]
It remains stuck in a loop see below text file for full log and here is a preview of what kinds of outputs it gives which seems to me is like a text formatting problem:
*****TASK LIST*****

 • \\n    Take into account these previously completed tasks: [\\\'\\\\\\\\\\\\\\\\n    Take into account these previously completed tasks: []\\\\\\\\\\\\\\\\n.\\\\\\\\\\\\\\\\n    Your task: Develop a task list\\\\\\\\\\\\\\\\nResponse:\\\\\\\\\\\\\\\\n    100\\\\\\\\\\\\\\\\n\\\\\\\\\\\\\\\\n    Task List:\\\\\\\\\\\\\\\\n    1. Create a sustainable food production system that can produce enough food to feed the entire population of the world, including developing countries and remote areas. This will involve using new technologies such as vertical farming and hydroponics, as well as traditional farming methods.\\\\\\\\\\\\\\\\n    2. Implement policies that encourage people to eat more plant-based diets, which are better for the environment and can help reduce food waste. This could include subsidies for farmers who grow fruits and vegetables, and education campaigns to promote the benefits of\\\\\\\'}.", \\\\\\\'    This result was based on this task description: Develop a task list. These are incomplete tasks: .\\\\\\\', \\\\\\\'    Based on the result, create new tasks to be completed by the AI system that do not overlap with incomplete tasks.\\\\\\\', \\\\\\\'    Return the tasks as an array.\\\\\\\', \\\\\\\'    \\\\\\\', \\\\\\\'    """\\\\\\\', \\\\\\\'    # Get the list of all completed tasks and their results\\\\\\\', \\\\\\\'    completed_tasks = get_completed_tasks()\\\\\\\', \\\\\\\'    \\\\\\\', \\\\\\\'    # Create a new task list\\\\\\\', \\\\\\\'    new_tasks = []\\\\\\\', \\\\\\\'    \\\\\\\', \\\\\\\'    # Iterate through each completed task\\\\\\\', \\\\\\\'    for task in completed_tasks:\\\\\\\', \\\\\\\'        # Get the name of the last completed task\\\\\\\', \\\\\\\'        last_task = task.split(\'\\n\\\\\\\')[-1]\\\\\\\', \\\\\\\'        # Get the result of the last completed task as a dictionary object\\\\\\\', \\\\\\\'        last_result = eval(last_task) or {}\\\\\\\', \\\\\\\'        # Extract the objective and tasks from the result object\\\\\\\', \\\\\\\'
 
[(babyagi) Dbabyagipython babyagi.py.txt](https://github.com/yoheinakajima/babyagi/files/11290754/babyagi.Dbabyagipython.babyagi.py.txt)

**Comment by francip** [comment]
Finally found the exact llama.cpp bindings this uses - https://github.com/abetlen/llama-cpp-python
Would've been useful to add this to requirements.  :-)
Will look into merging this later tonight.

**Comment by francip** [comment]
Nevermind, I should not read stuff before I drink my coffee. I'll look into merging this tonight.

**Review by francip — APPROVED** [review]

**Comment by francip** [comment]
Resolved the conflicts and will merge now. This will temporarily continue to use OpenAI embeddings while I figure out quick way to resolve this.

**Pull request merged**
