### PR TITLE
Add task list persistence through JSON file

### PR DESCRIPTION
**Pull request by Marouan-chak**
## Description
This PR adds the possibility to store the task list in a JSON file named "task_list.json". The "load_state()" and "save_state()" functions were added to enable the persistence. Now, if the "task_list.json" file exists, the task list and the task_id_counter will be loaded from task_list.json and task_id_counter.json. Additionally, a try-except block was added to catch the KeyboardInterrupt exception and save the state before exiting the while loop.
## Motivation and Context
Storing the task list in a file enables the script to resume from where it left off, even after being interrupted or restarted. This is useful when working with long-running scripts.

### CODE REVIEW

**Comment by digi604** [comment]
only saves last few tasks. should save task status and results

**Comment by Marouan-chak** [comment]
@digi604 I've updated the script to save the task status and results in a separate JSON file called `task_status_results.json`. This will ensure that we keep track of the completed tasks and their results throughout the script's execution. Please take a look at the updated changes and let me know if you have any further suggestions or concerns.

**Comment by yoheinakajima** [comment]
Ohhh I like this. Appreciate the patience as I find time to review PRs at night after getting kids down! (Currently looking through quickly between meetings)

**Comment by Macx2** [comment]
Alright

**Comment by francip** [comment]
@yoheinakajima I like having persistence as well, but feels like this is another change that can be refactored as a small extension loaded only if the user enables it in the .env

**Pull request closed without merging**
