### PR TITLE
Python formatting and fix typos

### PR DESCRIPTION
**Pull request by giorgiop**

### CODE REVIEW

**Comment by davidbyttow** [comment]
What did you use as a formatter? Was thinking of adding `black` or something similar

**Comment by francip** [comment]
Good cleanup, unfortunately too many other things got merged. Can you rebase and resolve conflicts and I'll merge?

**Review by francip — APPROVED** [review]

**Comment by giorgiop** [comment]
> What did you use as a formatter? Was thinking of adding `black` or something similar

yes that was black

**Comment by Podidiving** [comment]
Great idea to clean up code! 
I have a couple of suggestions: 
- add isort checking
- add linting tool (e.g. flake8) 
- create `Makefile` with targets to automatically reformat/lint all the code before contributing
- update Readme (contributing section), something like "format your code before you commit it"
- (Optionally) make `setup.cfg` file to introduce custom code style. E.g. I think that default line lengths can be extended a little bit (let's say `max-line-length=100` or something like that)

**Pull request closed without merging**
