### PR TITLE
Add support for weaviate

### LINKED ISSUE #239: Add support for weaviate
Add support for [weaviate](https://github.com/weaviate/weaviate) as an option for the memory store

### PR DESCRIPTION
**Pull request by hsm207**
Fixes #239

### CODE REVIEW

**Review by francip — APPROVED** [review]

**Comment by francip** [comment]
Looks good for the most part. The only nitpick I have is the fallback logic. Here's what I'd like to see (but we can do as follow up)

1. Check if Weaviate env variable there
2. If Yes, check if Weaviate is installed and can be loaded
3. If Yes, everything's peachy
4. If Weaviate env variable not there or Weaviate not installed, check Pinecone (same algo as above)
5. If Pinecone fails, use Chroma.

With the current implementation, if Weaviate is turned on, but fails, it directly goes to Chroma. Not a big issue, as allegedly people that try to configure Weaviate don't care about Pinecone... :-)

**Comment by hsm207** [comment]
> * Check if Weaviate env variable there
> * If Yes, check if Weaviate is installed and can be loaded
> * If Yes, everything's peachy
> * If Weaviate env variable not there or Weaviate not installed, check Pinecone (same algo as above)
> * If Pinecone fails, use Chroma.

@francip I've refactored the fallback logic based on your feedback. All good?

**Comment by francip** [comment]
Looks good. Let's merge it in... (It's still a draft rn, so I can't :-) )

**Comment by francip** [comment]
Are we landing this or what? :-p

**Comment by hsm207** [comment]
it will be ready to merge in a couple of days. @zainhas is making some final touches on the docs 😀

**Comment by hsm207** [comment]
@francip we're done with the docs

**Comment by francip** [comment]
Thanks! Merged.

**Pull request merged**
