### PR TITLE
Remove Pinecone dependency using Chroma

### PR DESCRIPTION
**Pull request by atroyn**
This PR replaces Pinecone with Chroma. This considerably simplifies getting babyagi up and running, since it now requires one less external API.

Users no longer need a Pinecone API key, or to worry about costs related to the task store - it all runs locally with Chroma, and is persisted on shutdown / exit of the agent.

This also allows users to easily share previously saved tasks, since Chroma simply stores the task table in a directory.

### CODE REVIEW

**Comment by micromysore** [comment]
the changes are a mix of formatting fixes and pinecone replacements. Could you please remove any formatting changes from this PR ? Thanks.

**Comment by OannesGPT** [comment]
I still run in the same error initiating when trying to install the sentencepiece for ChromaDB 
ERROR: Failed building wheel for sentencepiece
  Running setup.py clean for sentencepiece
Failed to build sentencepiece

**Comment by atroyn** [comment]
@OannesGPT this is an issue with upstream packages - notably, pytorch and ONNX don't yet support python 3.11.

**Comment by OannesGPT** [comment]
> 

Thank you for confirming what I painstakingly deduced from trail and error! Is it possible to have python 3.10 installed aswell or do I have to reverse my installation of python completely and wait with updating?

**Comment by atroyn** [comment]
@OannesGPT - you can just create a python 3.10 virtualenv, it shouldn't affect anything else.

**Comment by francip** [comment]
I'd love to have local database alternative to Pinecone. However, I also like to be able to choose between Chroma and Weaviate that was proposed in another PR. So we need a pluggable extension that people can easily enable.

Btw, Pinecone does solve one specific need - non-devs being able to quickly and easily run BabyAGI. Both Chroma and Weaviate do require a bit more setup (afaict, but I might be wrong here).

**Comment by atroyn** [comment]
Chroma requires no additional setup that installing the babyagi requirements, and in fact requires less setup than both weaviate and pinecone. 

If a user installs with this version, they don't even need to specify any environment variables - babyagi will just immediately run.

**Pull request closed without merging**
